using System;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.VectorData;
using Microsoft.SemanticKernel.Connectors.InMemory;
using ModelContextProtocol.Server;
using ReasonMCP.Models;

namespace ReasonMCP.Tools
{
    /// <summary>
    /// Exposes the SQLite Vector store to Reason via MCP for semantic knowledge retrieval.
    /// </summary>
    public class KnowledgeSearchTool
    {
        private readonly VectorStoreCollection<string, KnowledgeRecord> _collection;
        private readonly IEmbeddingGenerator<string, Embedding<float>> _embeddingGenerator;
        private readonly ILogger<KnowledgeSearchTool> _logger;

        public KnowledgeSearchTool(
            VectorStoreCollection<string, KnowledgeRecord> collection,
            IEmbeddingGenerator<string, Embedding<float>> embeddingGenerator,
            ILogger<KnowledgeSearchTool> logger
        )
        {
            _collection = collection;
            _embeddingGenerator = embeddingGenerator;
            _logger = logger;
        }

        /// <summary>
        /// Searches the ingested codebase and ADRs for relevant context.
        /// NOTE: Add your specific MCP tool attribute here (e.g.,[McpTool("search_knowledge")] or [KernelFunction])
        /// depending on the exact MCP SDK library you are utilizing.
        /// </summary>
        /// <param name="query">The semantic search query generated by Reason.</param>
        /// <param name="maxResults">The maximum number of chunks to return (defaults to 5 to protect token limits).</param>
        [McpServerTool]
        [Description("Allows the Reason AI coding agent to search the vector store for additional infomation to answer a query.")]
        public async Task<string> SearchKnowledgeBaseASync(
            [Description("The query to use for searching the vector store")] string query,
            [Description("The maximum number of query results")] int maxResults = 5,
            [Description("Cancellation Token")] CancellationToken cancellationToken = default
        )
        {
            //  1.  Gaurd Clause
            if (string.IsNullOrWhiteSpace(query))
            {
                return "Search query was empty.  Please provide a specific technical topic to search.";
            }

            _logger.LogInformation("Reason invoked knowledge search for: '{Query}'", query);

            try
            {
                //  2.  Convert Reason's text query into a 768-dimension vector
                var queryEmbedding = await _embeddingGenerator.GenerateAsync(
                    new[] { query },
                    cancellationToken: cancellationToken
                );

                var searchVector = queryEmbedding.First().Vector;

                //  3.  Configure the search options
                var searchOptions = new VectorSearchOptions<KnowledgeRecord>
                {
                    //Top = maxResults,
                    //  We only need the text and metadata returned, not the massive float array
                    IncludeVectors = false
                };

                //  4.  Execute the vectorize search against SQLite
                var searchResults = _collection.SearchAsync(
                    searchVector,
                    top: maxResults,
                    searchOptions,
                    cancellationToken
                );

                //  5.  Format the output deterministically for the LLLM
                return await FormatResultsForLlmAsync(query, searchResults, cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error occurred during vector search for query: {Query}", query);
                return $"System Error: Unable to retrieve knowledge at this time. Details: {ex.Message}";
            }
        }

        private static async Task<string> FormatResultsForLlmAsync(
            string query,
            IAsyncEnumerable<VectorSearchResult<KnowledgeRecord>> searchResults,
            CancellationToken cancellationToken
        )
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Knowledge Search Results for: '{query}'");

            int resultCount = 0;

            //  Microsoft.Extensions.VectorData returns an IAsyncEnumerable,
            //  We use await foreach to stream the results safely
            await foreach (var result in searchResults)
            {
                resultCount++;
                sb.AppendLine($"## Source: {result.Record.Source} (Chunk: {result.Record.ChunkIndex})");
                sb.AppendLine($"> **Topic:** {result.Record.Topic} | **Context:** {result.Record.HeaderContext}");

                // Exposing the score helps Reason determine if it's a weak or strong match
                sb.AppendLine($"> **Relevance Score:** {result.Score:F4}");
                sb.AppendLine("```text");
                sb.AppendLine(result.Record.Text);
                sb.AppendLine("```");
                sb.AppendLine("---");

            }

            if (resultCount == 0)
            {
                return $"No relevant information found in the knowledge base for '{query}'.";
            }

            return sb.ToString();
        }
    }
}