using System.ComponentModel;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.VectorData;
using Microsoft.SemanticKernel;
using ModelContextProtocol.Server;
using ReasonMCP.Interfaces.IEnrichment;
using ReasonMCP.Models;

namespace ReasonMCP.Tools
{
    /// <summary>
    /// Exposes the SQLite Vector store to Reason via MCP for semantic knowledge retrieval.
    /// </summary>
    public class ReferenceContextSearchTool
    {
        private readonly VectorStoreCollection<string, ReferenceVectorModel> _collection;
        private readonly IEmbeddingGenerator<string, Embedding<float>> _embeddingGenerator;
        private readonly IVectorSearchResultService _vectorSearchResultService;
        private readonly ILogger<ReferenceContextSearchTool> _logger;

        public ReferenceContextSearchTool(
            VectorStoreCollection<string, ReferenceVectorModel> collection,
            IEmbeddingGenerator<string, Embedding<float>> embeddingGenerator,
            IVectorSearchResultService vectorSearchResultService,
            ILogger<ReferenceContextSearchTool> logger
        )
        {
            _collection = collection;
            _embeddingGenerator = embeddingGenerator;
            _vectorSearchResultService = vectorSearchResultService;
            _logger = logger;
        }

        /// <summary>
        /// Searches the ingested Microsoft Reference documentations for relevant context.
        /// NOTE: Add the specific MCP tool attribute here (e.g.,[McpTool("documents_context")] or [KernelFunction])
        /// depending on the exact MCP SDK library you are utilizing.
        /// </summary>
        /// <param name="query">The semantic search query generated by Reason.</param>
        /// <param name="maxResults">The maximum number of chunks to return (defaults to 5 to protect token limits).</param>
        [McpServerTool(Name = "reference_context_search")]
        [KernelFunction("reference_context_search")]
        [Description("Allows agents to search the vector store for additional information to answer using the Codebase ")]
        public async Task<string> SearchReferenceContextAsync(
            [Description("The query to use for searching the Reference vector store")] string query,
            [Description("The maximum number of query results")] int maxResults = 5,
            [Description("Cancellation Token")] CancellationToken cancellationToken = default
        )
        {
            //  1.  Gaurd Clause
            if (string.IsNullOrWhiteSpace(query))
            {
                return "Search query was empty.  Please provide a specific technical topic to search.";
            }

            _logger.LogInformation("Reason invoked CodebaseContext search for: '{Query}'", query);

            try
            {
                //  2.  Convert Reason's text query into a 768-dimension vector
                var queryEmbedding = await _embeddingGenerator.GenerateAsync(
                    new[] { query },
                    cancellationToken: cancellationToken
                );

                var searchVector = queryEmbedding.First().Vector;

                //  3.  Configure the search options
                var searchOptions = new VectorSearchOptions<ReferenceVectorModel>
                {
                    //Top = maxResults,
                    //  We only need the text and metadata returned, not the massive float array
                    IncludeVectors = false
                };

                //  4.  Execute the vectorize search against SQLite
                var searchResults = _collection.SearchAsync(
                    searchVector,
                    top: maxResults,
                    searchOptions,
                    cancellationToken
                );

                // The DocumentVectorModel class (in ReasonMCP.Models) must implement
                // the IEnrichmentVectorModel interface (in ReasonMCP.Interfaces.IEnrichment)
                // for this call to compile successfully.
                //  5.  Format the output deterministically for the LLLM
                return await _vectorSearchResultService.FormatForLlamaAsync(
                    searchResults,
                    query,
                    "Reference",
                    cancellationToken
                );
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error occurred during vector search for query: {Query}", query);
                return $"System Error: Unable to retrieve knowledge at this time. Details: {ex.Message}";
            }
        }
    }
}