using Microsoft.AspNetCore.Http;
using Microsoft.SemanticKernel.ChatCompletion;
using ReasonMCP.Core.DTOs;
namespace ReasonMCP.Core.Utilities
{
    public static class EndpointResponseUtility
    {
        public static IResult CheckResponseErrors(
            VSCodeChatPayloadDto payload,
            ChatHistory response
        )
        {
            var agent = payload.AgentId;
            //  Don't just return the response, Let's check for errors
            //  1.  Check if the object itself is null
            if (response == null)
            {
                return Results.BadRequest(
                    new
                    {
                        error = "No response history was generated."
                    }
                );
            }

            //  2.  Find the last message generated by the Assistant
            var lastAssistantMessage = response
                .LastOrDefault(m => m.Role == AuthorRole.Assistant);

            //  3.  Validate that an assistant message exists and is not empty
            if (lastAssistantMessage == null ||
                string.IsNullOrWhiteSpace(lastAssistantMessage.Content))
            {
                return Results.BadRequest(
                    new
                    {
                        error = $"{agent} failed to generate a response."
                    }
                );
            }

            //  4.  Check for SemanticKernel-specific metadata errors
            if (lastAssistantMessage.Metadata != null &&
                lastAssistantMessage.Metadata.ContainsKey("Error"))
            {
                var errorMessage = lastAssistantMessage.Metadata["Error"]?.ToString()
                    ?? "An unknown error occurred during generation.";

                return Results.BadRequest(
                    new
                    {
                        error = errorMessage
                    }
                );
            }

            //  5.  No Errors detected, return original response
            return Results.Ok(
                new
                {
                    response
                }
            );
        }
    }
}